Updated config details

diff --git a/versionmanager b/versionmanager
--- a/versionmanager
+++ b/versionmanager
@@ -42,28 +42,59 @@ get_config() {
     if [ ! -f $CFG_NAME ]; then
         echo "You don't have a CFG_NAME file? Well, here's mine. Check the file $CFG_NAME!"
 cat << EOF > $CFG_NAME
-###############################################
-#       Config file for Version Manager       #
-###############################################
-# This place is whitespace sensitive! Values with whitespaces are ignore.
-# Keep everything as \`: <value>\`. Exactly one space between and any spaces in value is ignored.
-#   If you know regex. it's basically just \`^\$[^:]*: <value>\`. If you can read this, it's clear that setting doesn't
-#   care if there's spaces or not. If you're adding your own, just make sure you add your own logic in the script.
-#   Check the README.md if you need help with this part.
+#############################################################################################################################
+#                                              Config file for Version Manager                                              #
+#############################################################################################################################
+# This place is whitespace sensitive! Values with whitespaces are ignore.                                                   #
+# Keep everything as \`\$<key>: <value>\`. Exactly one space between and any spaces in value is ignored.                    #
+#   If you know regex. it's basically just \`^\$[^:]*: <value>\`. If you can read this, it's clear that setting doesn't.    #
+#   care if there's spaces or not. If you're adding your own, just make sure you add your own logic in the script.          #
+#   Check the README.md if you need help with this part.                                                                    #
+# There's a lot of comment text here. If it's easier on the eyes, you can delete all the comments below to see all the      #
+# nice config stuff. You can always go to the README to view the details again.                                             #
+#############################################################################################################################                                                            
 
 # Delimeters in version string. It's the stuff that separates the numbers and words like "alpha", "beta", etc.
 # Default is \`-.\`, you'll see later.
 \$delims: -.
 
-# Your version format. It's all the numbers and stuff.
-# Some ground rules though:
-#       **THERE MUST BE AT LEAST ONE COMPONENT**
-#       Make sure you use the delims to separate them! We don't want a "majorminor" component do we?
-#       If you want to specify release stage (e.g. beta, alpha), name it \`release\`. Otherwise, we assume there isn't.
-#           All occurences of \`release\` will be updated simultaneously.
+# Specify your version format here.
+# This is the important part, so let's get techincal:
+#       -   There must be AT LEAST ONE COMPONENT.
+#       -   Use the delims from earlier to separate components. Otherwise you'll get something like "majorminor" as a component label.
+#       -   If you want to specify a release stage (e.g. beta, alpha, rel, etc.), name the component as \`release\`. 
+#           Otherwise, we assume there isn't one.
+#           -   All occurences of \`release\` will be updated simultaneously should you update (via command).
+#       -   For all components (excluding \`release\`), decimal numbers are assumed unless a formatter is used.
+#
+# Formatters:
+#   Format codes that can be placed after a component label by using {<format_code>}
+#   Formatters are used to specify specific behaviors of each component when the manager updates things.
+#   For example: release-major.minor.patch-dev{x3}
+#
+#   Format Codes:
+#       -   Hexadecimals: x<int>
+#               Increments with hexadecimals of length <int> instead of decimals.
+#       -   Random: r<int>[s<per>]
+#               Generates a pseudo-random digit of length <int> instead.
+#               Use \`s\` to also include characters with <per> chance of appearance.
+#       -   Custom: c<cok>
+#               Uses your own custom code order specified via <cok>.
+#   Tag Values:
+#       <int>: a non-empty, non-zero (> 0) integer.
+#       <per>: percentage (<int>%. 0=100%).
+#       <cok>: custom order key of your custom code order. You can set this at the buttom under "Custom Code Zone"
 # Default is \`release-major.minor.patch\`.
 \$format: release-major.minor.patch
 
+# Custom Code Zone
+# This doesn't work yet, nor is it implemented yet. But I'm gonna need it soon, so putting it here for now.
+# This is where you put your <cok> key-value pairs.
+# All custom coder orders must follow config key-value pairs syntax (read at top of this config).
+# Remember any spaces or white spaces in the values field is ignored. Use underscores "_" instead.
+# Try to keep it one-line for now. We want to later allow multi-line ordering.
+# This is an example entry:
+# \$rels: alpha,beta,charlie
 EOF
         exit 1
     else
@@ -109,11 +140,17 @@ get_version_data() {
 
         # Inefficient, but good for one time. Build default version again before doing it later for real.
         local version_vals=($(echo ${VERSION_FORMAT[@]} | sed "s/[^ ]*/0/g"))
+        local i=0
         for ((i = 0; i < NUM_VERSION_VALS; i++)); do
-            if [[ "${VERSION_FORMAT[i]}" == "release" ]]; then
+            PART="${VERSION_FORMAT[i]}"
+            if [[ "$PART" == "release" ]]; then
                 version_vals[$i]="alpha"
+            else
+                reset_val
+                version_vals[$i]=$NEW_VAL
             fi
         done
+
         rebuild_version "${version_vals[@]}"
         export_json
 
@@ -128,6 +165,7 @@ rebuild_version() {
     local version_vals=($@)
 
     local full_version=""
+    local i=0
     for ((i = 0; i < NUM_VERSION_VALS; i++)); do
         # Add the delims
         if [ $i -ne 0 ]; then
@@ -147,6 +185,58 @@ export_json() {
     "version": "$FULL_VERSION"
 }
 EOF
+}
+
+OLD_VAL=""
+PART=""
+NEW_VAL=""
+increase_val() {    # NOTE: OLD_VAL, PART are expected to have been defined. Do not use until after OLD_VAL is defined.
+    if [[ -z $OLD_VAL ]] || [[ -z $PART ]]; then
+        return 1    # Observe the note
+    fi
+
+    local hex_check=$(echo "$PART" | grep -E "{x[0-9]+}")
+    if [[ -z $hex_check ]]; then
+        NEW_VAL=$(($OLD_VAL + 1))
+    else
+        local num_hexes="${PART#*x}"
+        num_hexes="${num_hexes%\}}"
+        if [ $num_hexes -lt 1 ]; then
+            echo "Whoa there, number of hex digits must be >= 1 and non-empty in the format! Version values could be broken, check that too!"
+            exit 1
+        fi
+        
+        local hex_as_dec=$((16#${OLD_VAL}))
+        hex_as_dec=$((hex_as_dec + 1))
+        
+        local hex_val=$(printf "%0${num_hexes}x" "$hex_as_dec")
+        hex_val="${hex_val: -num_hexes}"
+        NEW_VAL=$hex_val
+    fi
+}
+
+reset_val() {
+    if [[ -z $PART ]]; then
+        return 1    # Observe the note
+    fi
+
+    local hex_check=$(echo "$PART" | grep -E "{x[0-9]*}")
+    if [[ -z $hex_check ]]; then
+        NEW_VAL=0
+    else
+        local num_hexes="${PART#*x}"
+        num_hexes="${num_hexes%\}}"
+        echo $num_hexes
+
+        if [ $num_hexes -lt 1 ] || [[ -z $num_hexes ]]; then
+            echo "Whoa there, number of hex digits must be >= 1 and non-empty in the format!"
+            exit 1
+        fi
+
+        local hex_val=$(printf "%0${num_hexes}x" "0")
+        hex_val="${hex_val: -num_hexes}"
+        NEW_VAL=$hex_val
+    fi
 }
 
 ########################
@@ -201,9 +291,11 @@ for ((i = 0; i < NUM_VERSION_VALS; i++)); do
             VERSION_VALS[i]=$RELEASE
         fi
     elif [ $i -eq $VER_LVL ]; then
-        VERSION_VALS[i]=$(($OLD_VAL + 1))
+        increase_val
+        VERSION_VALS[i]=$NEW_VAL
     elif [ $i -gt $VER_LVL ]; then
-        VERSION_VALS[i]=0
+        reset_val
+        VERSION_VALS[i]=$NEW_VAL
     fi
 
     echo -e "\tUpdated $PART [\033[1;33m$OLD_VAL -> ${VERSION_VALS[i]}\033[0m]"
